#!/usr/bin/python

nsmap = { "anim": "urn:oasis:names:tc:opendocument:xmlns:animation:1.0",
          "chart": "urn:oasis:names:tc:opendocument:xmlns:chart:1.0",
          "config": "urn:oasis:names:tc:opendocument:xmlns:config:1.0",
          "css3t": "http://www.w3.org/TR/css3-text/",
          "dc": "http://purl.org/dc/elements/1.1/",
          "dom": "http://www.w3.org/2001/xml-events",
          "dr3d": "urn:oasis:names:tc:opendocument:xmlns:dr3d:1.0",
          "draw": "urn:oasis:names:tc:opendocument:xmlns:drawing:1.0",
          "drawooo": "http://openoffice.org/2010/draw",
          "field": "urn:openoffice:names:experimental:ooo-ms-interop:xmlns:field:1.0",
          "fo": "urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0",
          "form": "urn:oasis:names:tc:opendocument:xmlns:form:1.0",
          "formx": "urn:openoffice:names:experimental:ooxml-odf-interop:xmlns:form:1.0",
          "grddl": "http://www.w3.org/2003/g/data-view#",
          "manifest": "urn:oasis:names:tc:opendocument:xmlns:manifest:1.0",
          "math": "http://www.w3.org/1998/Math/MathML",
          "meta": "urn:oasis:names:tc:opendocument:xmlns:meta:1.0",
          "number": "urn:oasis:names:tc:opendocument:xmlns:datastyle:1.0",
          "of": "urn:oasis:names:tc:opendocument:xmlns:of:1.2",
          "office": "urn:oasis:names:tc:opendocument:xmlns:office:1.0",
          "officeooo": "http://openoffice.org/2009/office",
          "ooo": "http://openoffice.org/2004/office",
          "oooc": "http://openoffice.org/2004/calc",
          "ooow": "http://openoffice.org/2004/writer",
          "presentation": "urn:oasis:names:tc:opendocument:xmlns:presentation:1.0",
          "rpt": "http://openoffice.org/2005/report",
          "script": "urn:oasis:names:tc:opendocument:xmlns:script:1.0",
          "smil": "urn:oasis:names:tc:opendocument:xmlns:smil-compatible:1.0",
          "style": "urn:oasis:names:tc:opendocument:xmlns:style:1.0",
          "svg": "urn:oasis:names:tc:opendocument:xmlns:svg-compatible:1.0",
          "table": "urn:oasis:names:tc:opendocument:xmlns:table:1.0",
          "tableooo": "http://openoffice.org/2009/table",
          "text": "urn:oasis:names:tc:opendocument:xmlns:text:1.0",
          "xforms": "http://www.w3.org/2002/xforms",
          "xhtml": "http://www.w3.org/1999/xhtml",
          "xlink": "http://www.w3.org/1999/xlink",
          "xsd": "http://www.w3.org/2001/XMLSchema",
          "xsi": "http://www.w3.org/2001/XMLSchema-instance" }

for term in ("CHART_style_name", "CONFIG_config_item",
             "CONFIG_config_item_set", "CONFIG_name", "DRAW_class_names",
             "DRAW_custom_shape", "DRAW_display_name",
             "DRAW_fill_gradient_name", "DRAW_fill_hatch_name",
             "DRAW_fill_image", "DRAW_fill_image_name", "DRAW_gradient",
             "DRAW_hatch", "DRAW_marker", "DRAW_marker_end",
             "DRAW_marker_start", "DRAW_master_page_name", "DRAW_name",
             "DRAW_opacity", "DRAW_opacity_name", "DRAW_page",
             "DRAW_stroke_dash", "DRAW_stroke_dash_names", "DRAW_style_name",
             "DRAW_text_style_name", "FO_margin_bottom", "FO_margin_top",
             "FORM_text_style_name", "MANIFEST_file_entry",
             "MANIFEST_full_path", "MANIFEST_manifest", "MANIFEST_media_type",
             "MANIFEST_version", "META_generator", "NUMBER_date_style",
             "OFFICE_automatic_styles", "OFFICE_body",
             "OFFICE_document_content", "OFFICE_document_meta",
             "OFFICE_document_settings", "OFFICE_document_styles",
             "OFFICE_foo", "OFFICE_master_styles", "OFFICE_meta",
             "OFFICE_presentation", "OFFICE_scripts", "OFFICE_settings",
             "OFFICE_styles", "OFFICE_version", "PRESENTATION_class_names",
             "PRESENTATION_notes",
             "PRESENTATION_presentation_page_layout_name",
             "PRESENTATION_style_name", "STYLE_apply_style_name",
             "STYLE_data_style_name", "STYLE_display_name",
             "STYLE_leader_text_style", "STYLE_list_style_name",
             "STYLE_master_page", "STYLE_master_page_name", "STYLE_name",
             "STYLE_next_style_name", "STYLE_page_layout",
             "STYLE_page_layout_name", "STYLE_paragraph_properties",
             "STYLE_parent_style_name", "STYLE_percentage_data_style_name",
             "STYLE_presentation_page_layout",
             "STYLE_register_truth_ref_style_name", "STYLE_style",
             "STYLE_style_name", "STYLE_text_line_through_text_style",
             "SVG_x", "SVG_y", "TABLE_default_cell_style_name", 
             "TABLE_paragraph_style_name", "TABLE_style_name",
             "TABLE_table_template", "TABLE_template_name",
             "TEXT_citation_body_style_name", "TEXT_citation_style_name",
             "TEXT_class_names", "TEXT_cond_style_name", "TEXT_date",
             "TEXT_default_style_name", "TEXT_list", "TEXT_list_style",
             "TEXT_main_entry_style_name", "TEXT_master_page_name", "TEXT_p",
             "TEXT_style_name", "TEXT_style_override", "TEXT_tab",
             "TEXT_visited_style_name", "XLINK_href"):
    (ns, e) = term.split("_", 1)
    vars()[term] = "{" + nsmap[ns.lower()] + "}" + e.replace("_", "-")

del e, ns, term
